
CREATE TABLE OAUTH_ACCESS_TOKEN (
  TOKEN_ID VARCHAR2(256) NOT NULL,
  TOKEN BLOB,
  AUTHENTICATION_ID VARCHAR2(256) ,
  USER_NAME VARCHAR2(256) ,
  CLIENT_ID VARCHAR2(256) ,
  AUTHENTICATION BLOB,
  REFRESH_TOKEN VARCHAR2(256) ,
  PRIMARY KEY (TOKEN_ID)
);
 
CREATE TABLE OAUTH_CLIENT_DETAILS (
  CLIENT_ID VARCHAR2(256) NOT NULL,
  RESOURCE_IDS VARCHAR2(256) ,
  CLIENT_SECRET VARCHAR2(256) ,
  SCOPE VARCHAR2(256) ,
  AUTHORIZED_GRANT_TYPES VARCHAR2(256) ,
  WEB_SERVER_REDIRECT_URI VARCHAR2(256) ,
  AUTHORITIES VARCHAR2(256) ,
  ACCESS_TOKEN_VALIDITY NUMBER(11) ,
  REFRESH_TOKEN_VALIDITY NUMBER(11) ,
  ADDITIONAL_INFORMATION VARCHAR2(2000) ,
  AUTOAPPROVE VARCHAR2(256) ,
  PRIMARY KEY (CLIENT_ID)
);
 
CREATE TABLE OAUTH_CODE (
  CODE VARCHAR2(256) ,
  AUTHENTICATION BLOB
);
 
CREATE TABLE OAUTH_REFRESH_TOKEN (
  TOKEN_ID VARCHAR2(256) ,
  TOKEN BLOB,
  AUTHENTICATION BLOB
);
 
INSERT INTO OAUTH_CLIENT_DETAILS (CLIENT_ID,RESOURCE_IDS,CLIENT_SECRET,SCOPE,AUTHORIZED_GRANT_TYPES,WEB_SERVER_REDIRECT_URI,AUTHORITIES,ACCESS_TOKEN_VALIDITY,REFRESH_TOKEN_VALIDITY,ADDITIONAL_INFORMATION,AUTOAPPROVE) VALUES ('clientapp','restservice','123456','read,write','password,refresh_token','','USER',64800,NULL,'{}','');
 